# Generated by Django 5.2 on 2025-05-28 06:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Creative', 'Creative'), ('Analytical', 'Analytical'), ('Collaborative', 'Collaborative')], max_length=50),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='confidence_score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Creative', 'Creative'), ('Analytical', 'Analytical'), ('Collaborative', 'Collaborative')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('student', 'question')},
        ),
    ]
