# Generated by Django 5.2 on 2025-05-28 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_alter_career_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerrecommendation',
            name='career',
        ),
        migrations.RemoveField(
            model_name='careerrecommendation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='recommendation',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='new_app_que_categor_9e0c4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='new_app_stu_email_24602c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='career',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='option',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='feedback',
            name='career',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_app.career'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='new_app.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CareerRecommendation',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='created_at',
        ),
    ]
