# Generated by Django 4.2.7 on 2025-09-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0009_performanceprediction_notification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("academic", "Academic"),
                            ("career", "Career Guidance"),
                            ("technical", "Technical Support"),
                            ("registration", "Registration"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="feedback_type",
            field=models.CharField(
                choices=[
                    ("academic", "Academic"),
                    ("behavioral", "Behavioral"),
                    ("career", "Career"),
                    ("general", "General"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="parent_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="feedback",
            name="parent_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="feedback",
            name="parent_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="feedback",
            name="student_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="student_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="feedback",
            name="subject",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="feedback",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="new_app.teacher",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="teacher_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="career",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="new_app.career",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                (
                    "grade_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("midterm", "Midterm"),
                            ("final", "Final"),
                            ("assignment", "Assignment"),
                            ("project", "Project"),
                        ],
                        max_length=50,
                    ),
                ),
                ("score", models.FloatField()),
                ("max_score", models.FloatField(default=100)),
                ("percentage", models.FloatField()),
                ("date", models.DateField(auto_now_add=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_app.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_app.teacher",
                    ),
                ),
            ],
        ),
    ]
