# Generated by Django 4.2.7 on 2025-09-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0010_faq_feedback_feedback_type_feedback_parent_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accuracy_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Very Inaccurate"),
                            (2, "Inaccurate"),
                            (3, "Somewhat Accurate"),
                            (4, "Accurate"),
                            (5, "Very Accurate"),
                        ]
                    ),
                ),
                (
                    "usefulness_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Not Useful"),
                            (2, "Slightly Useful"),
                            (3, "Moderately Useful"),
                            (4, "Useful"),
                            (5, "Very Useful"),
                        ]
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("actual_grade", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_app.performanceprediction",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_app.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("midterm", "Midterm"),
                            ("final", "Final"),
                            ("assignment", "Assignment Due"),
                            ("project", "Project Due"),
                        ],
                        max_length=50,
                    ),
                ),
                ("exam_date", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("students", models.ManyToManyField(to="new_app.student")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_app.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=200)),
                ("course_description", models.TextField()),
                (
                    "reason",
                    models.TextField(
                        help_text="Why this course is suggested based on performance"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical - Immediate attention needed"),
                            ("high", "High - Important for improvement"),
                            ("medium", "Medium - Recommended"),
                            ("low", "Low - Optional enhancement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("based_on_grade", models.FloatField(blank=True, null=True)),
                ("based_on_attendance", models.FloatField(blank=True, null=True)),
                ("subject_area", models.CharField(max_length=100)),
                ("target_improvement", models.CharField(max_length=200)),
                ("resources_link", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_accepted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("student_feedback", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_app.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="new_app.teacher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "priority"],
            },
        ),
    ]
